import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { nunito } from "@/components/ui/fonts";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${nunito.className} antialiased`}
      >
        
        {children}
        <Toaster richColors position="top-right"  />
      </body>
    </html>
  );
}
